name: CraterLib
version: ${version}
description: "A Modding API used to create 'universal' mods"
main: com.hypherionmc.craterlib.paper.CraterLibPlugin
author: HypherionSA
api-version: '1.21'
bootstrapper: com.hypherionmc.craterlib.paper.CraterLibBootstrap
load: STARTUP
