modLoader = "javafml"
loaderVersion = "[46,)"
license = "MIT"
issueTrackerURL="https://github.com/firstdarkdev/craterLib/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL="https://modrinth.com/mod/craterlib"
logoFile = "craterlib_logo.png"
#credits="Thanks for this example mod goes to Java"
authors = "${mod_author}, Zenith"
description = '''
A library mod used by First Dark Development and HypherionSA Mods
'''
displayTest = "MATCH_VERSION"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"
