#Project
version_major=2
version_minor=1
version_patch=6
version_build=0

#Mod
mod_author=HypherionSA
mod_id=craterlib
mod_name=CraterLib
project_group=com.hypherionmc.craterlib

# Shared
minecraft_version=1.21.9

# Fabric
fabric_loader=0.16.13
fabric_api=0.133.14+1.21.9

# Forge
forge_version=59.0.5

# NeoForge
neoforge_version=16-beta

# Paper
paper_loader=59

# Non Minecraft Dependencies
moon_config=1.0.12
lombok=1.18.32
adventure=4.17.0
rpc_sdk=1.0
discord_formatter=2.0.0
cloth_config=17.0.144

# Mod Dependencies
# Fabric Only
fabrictailor=2.3.1
vanish=1.5.4+1.20.5
mod_menu_version=10.0.0-beta.1

# Shared
vanishmod=1.1.20
vanishmod_neo=ZqDGQbfq
ftb_essentials=2101.1.0
ftb_ranks=2101.1.1
player_revive=6889401
creative_core=6113754
advanced_chat=SNA4dye5

# Publishing
curse_id=867099
modrinth_id=Nn8Wasaq
release_type=experimental
supported_mc=1.21.9,1.21.10
displayed_versions=1.21.9/10

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
