#Project
version_major=3
version_minor=1
version_patch=3
version_build=0

#Mod
mod_author=HypherionSA
mod_id=craterlib
mod_name=CraterLib
project_group=com.hypherionmc.craterlib

# Shared
minecraft_version=26.1.2

# Fabric
fabric_loader=0.18.4
fabric_api=0.146.1+26.1.2

# Forge
forge_version=64.0.4

# NeoForge
neoforge_version=17-beta

# Paper
paper_loader=72

# Non Minecraft Dependencies
moon_config=1.0.13
adventure=4.26.1
discord_formatter=3.0.1
cloth_config=26.1.154

# Mod Dependencies
# Fabric Only
fabrictailor=2.9.1
vanish=1.6.8+26.1
mod_menu_version=18.0.0-alpha.8

# Shared
vanishmod=1.6.8+26.1
vanishmod_neo=iVEuBaPo
ftb_essentials=26.1.2.3
ftb_ranks=26.1.2.2
player_revive=7930067
creative_core=7930167
advanced_chat=WL6XScbT

# Publishing
curse_id=867099
modrinth_id=Nn8Wasaq
releaseType=release
supported_mc=26.1.2
displayed_versions=26.1.2

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
