modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/firstdarkdev/craterLib/issues"

[[mods]]
    modId = "${mod_id}"
    version = "${version}"
    displayName = "${mod_name}"
    displayURL = "https://modrinth.com/mod/craterlib"
    logoFile = "craterlib_logo.png"
    #credits="Thanks for this example mod goes to Java"
    authors = "${mod_author}, Zenith"
    description = '''
    A library mod used by First Dark Development and HypherionSA Mods
    '''
    displayTest = "NONE"

[[dependencies.${ mod_id }]]
    modId = "neoforge"
    type="required"
    required=true
    versionRange = "[20.4,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${ mod_id }]]
    modId = "minecraft"
    type="required"
    required=true
    versionRange = "[1.20.4,1.20.5)"
    ordering = "NONE"
    side = "BOTH"