#Project
version_major=3
version_minor=0
version_patch=0
version_build=0

#Mod
mod_author=HypherionSA
mod_id=craterlib
mod_name=CraterLib
project_group=com.hypherionmc.craterlib

# Shared
minecraft_version=1.18.2

# Fabric
fabric_loader=0.16.13
fabric_api=0.76.0+1.18.2

# Forge
forge_version=40.2.0

# NeoForge
neoforge_version=16-beta

# Paper
paper_loader=59

# Non Minecraft Dependencies
moon_config=1.0.12
lombok=1.18.32
adventure=4.17.0
discord_formatter=2.0.0
cloth_config=6.5.102

# Mod Dependencies
# Fabric Only
fabrictailor=1.9.0+1.18.2
vanish=1.1.0
mod_menu_version=3.2.5

# Shared
vanishmod=1.1.14
vanishmod_neo=ZqDGQbfq
ftb_essentials=1802.2.2-build.83
ftb_ranks=1802.1.11-build.71
player_revive=5335413
creative_core=5335387
advanced_chat=FNHLd87y

# Publishing
curse_id=867099
modrinth_id=Nn8Wasaq
release_type=release
supported_mc=1.18.2
displayed_versions=1.18.2

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
