#Project
version_major=3
version_minor=1
version_patch=0
version_build=0

#Mod
mod_author=HypherionSA
mod_id=craterlib
mod_name=CraterLib
project_group=com.hypherionmc.craterlib

# Shared
minecraft_version=1.21.5

# Fabric
fabric_loader=0.16.13
fabric_api=0.119.5+1.21.5

# Forge
forge_version=55.1.0

# NeoForge
neoforge_version=0-beta

# Paper
paper_loader=59

# Non Minecraft Dependencies
moon_config=1.0.12
adventure=4.26.1
discord_formatter=3.0.0
cloth_config=17.0.144

# Mod Dependencies
# Fabric Only
fabrictailor=2.3.1
vanish=1.5.4+1.20.5
mod_menu_version=10.0.0-beta.1

# Shared
vanishmod=1.1.20
vanishmod_neo=puxrKAMr
ftb_essentials=2101.1.0
ftb_ranks=2101.1.1
player_revive=6119534
creative_core=6113754
advanced_chat=CEJSc93h

# Publishing
curse_id=867099
modrinth_id=Nn8Wasaq
releaseType=release
supported_mc=1.21.5
displayed_versions=1.21.5

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
