#Project
version_major=3
version_minor=1
version_patch=3
version_build=0

#Mod
mod_author=HypherionSA
mod_id=craterlib
mod_name=CraterLib
project_group=com.hypherionmc.craterlib

# Shared
minecraft_version=26.3

# Fabric
fabric_loader=0.19.5
fabric_api=0.161.0+26.3

# Forge
forge_version=66.0.2

# NeoForge
neoforge_version=7-beta

# Paper
paper_loader=26

# Non Minecraft Dependencies
moon_config=1.0.13
adventure=4.26.1
discord_formatter=3.0.1
cloth_config=26.1.154

# Mod Dependencies
# Fabric Only
fabrictailor=2.10.0
vanish=1.6.15+26.3
mod_menu_version=21.0.0-beta.1

# Shared
vanishmod=1.6.8+26.1
vanishmod_neo=ZffjwCMj
ftb_essentials=26.1.2.3
ftb_ranks=26.1.2.2
player_revive=7930067
creative_core=7930167
advanced_chat=WL6XScbT

# Publishing
curse_id=867099
modrinth_id=Nn8Wasaq
releaseType=release
supported_mc=26.3
displayed_versions=26.3

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
