name: Test Orbit Auto PR

on:
  pull_request:
    branches:
      - porting

jobs:
  run-gradle-taks:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch all branches and tags
        run: git fetch --all

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Workspace
        run: chmod +x ./gradle && ./gradlew setupWorkspace

      - name: Test LTS Branches
        run: |
          for dir in dev/*/ ; do
            if [ -d "$dir" ]; then
              echo "Running Gradle build for $dir"
              cd "$dir"
              chmod +x ./gradlew
              ./gradlew build
              cd -
            fi
          done